### ISSUE TITLE
undefined method `prepare!' for class `ActionDispatch::Session::AbstractStore'

### ISSUE THREAD

**Issue by restebanez** [nbudin/devise_cas_authenticatable#17]
Hi there, 

devise_cas_authenticatable seems not to work in rails 3.1.1 and ruby 1.9.2-p290. After bundle install, i run: 

rails generate devise User, and i got this error:

/Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/activesupport-3.1.1/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method`prepare!' for class `ActionDispatch::Session::AbstractStore' (NameError)
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/activesupport-3.1.1/lib/active_support/core_ext/module/aliasing.rb:31:in`alias_method_chain'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/devise_cas_authenticatable-1.0.0.alpha12/lib/devise_cas_authenticatable/single_sign_out.rb:24:in `block in <top (required)>'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/devise_cas_authenticatable-1.0.0.alpha12/lib/devise_cas_authenticatable/single_sign_out.rb:19:in`class_eval'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/devise_cas_authenticatable-1.0.0.alpha12/lib/devise_cas_authenticatable/single_sign_out.rb:19:in `<top (required)>'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in`require'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in `block in require'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:223:in`block in load_dependency'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:223:in`load_dependency'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in `require'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/devise_cas_authenticatable-1.0.0.alpha12/lib/devise_cas_authenticatable.rb:8:in`<top (required)>'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:in `require'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:in`block (2 levels) in require'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:in `each'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:in`block in require'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:in `each'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:in`require'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/bundler-1.0.21/lib/bundler.rb:122:in `require'
    from /Users/restebanez/agi/config/application.rb:13:in`<top (required)>'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/railties-3.1.1/lib/rails/commands.rb:21:in `require'
    from /Users/restebanez/.rvm/gems/ruby-1.9.2-p290@agi/gems/railties-3.1.1/lib/rails/commands.rb:21:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

Here is my bundle list:

Gems included by the bundle:
- actionmailer (3.1.1)
- actionpack (3.1.1)
- activemodel (3.1.1)
- activerecord (3.1.1)
- activeresource (3.1.1)
- activesupport (3.1.1)
- arel (2.2.1)
- bcrypt-ruby (3.0.1)
- builder (3.0.0)
- bundler (1.0.21)
- coffee-rails (3.1.1)
- coffee-script (2.2.0)
- coffee-script-source (1.1.2)
- devise (1.4.8)
- devise_cas_authenticatable (1.0.0.alpha12)
- erubis (2.7.0)
- execjs (1.2.9)
- hike (1.2.1)
- i18n (0.6.0)
- jquery-rails (1.0.14)
- json (1.6.1)
- mail (2.3.0)
- mime-types (1.16)
- multi_json (1.0.3)
- orm_adapter (0.0.5)
- polyglot (0.3.2)
- rack (1.3.3)
- rack-cache (1.1)
- rack-mount (0.8.3)
- rack-ssl (1.3.2)
- rack-test (0.6.1)
- rails (3.1.1)
- railties (3.1.1)
- rake (0.9.2)
- rdoc (3.10)
- rubycas-client (2.2.1)
- sass (3.1.10)
- sass-rails (3.1.4)
- sprockets (2.0.2)
- sqlite3 (1.3.4)
- thor (0.14.6)
- tilt (1.3.3)
- treetop (1.4.10)
- tzinfo (0.3.30)
- uglifier (1.0.3)
- warden (1.0.6)

Thanks,

Rodrigo
